//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ReferenciaWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DCAlumno", Namespace="http://schemas.datacontract.org/2004/07/WCFAlumno")]
    [System.SerializableAttribute()]
    public partial class DCAlumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string curpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idEstadoOrigenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short idEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                if ((object.ReferenceEquals(this.correoField, value) != true)) {
                    this.correoField = value;
                    this.RaisePropertyChanged("correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string curp {
            get {
                return this.curpField;
            }
            set {
                if ((object.ReferenceEquals(this.curpField, value) != true)) {
                    this.curpField = value;
                    this.RaisePropertyChanged("curp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                if ((this.fechaNacimientoField.Equals(value) != true)) {
                    this.fechaNacimientoField = value;
                    this.RaisePropertyChanged("fechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstadoOrigen {
            get {
                return this.idEstadoOrigenField;
            }
            set {
                if ((this.idEstadoOrigenField.Equals(value) != true)) {
                    this.idEstadoOrigenField = value;
                    this.RaisePropertyChanged("idEstadoOrigen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short idEstatus {
            get {
                return this.idEstatusField;
            }
            set {
                if ((this.idEstatusField.Equals(value) != true)) {
                    this.idEstatusField = value;
                    this.RaisePropertyChanged("idEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primerApellidoField, value) != true)) {
                    this.primerApellidoField = value;
                    this.RaisePropertyChanged("primerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoApellidoField, value) != true)) {
                    this.segundoApellidoField = value;
                    this.RaisePropertyChanged("segundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaWCF.IWCFAlumno")]
    public interface IWCFAlumno {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/consultar", ReplyAction="http://tempuri.org/IWCFAlumno/consultarResponse")]
        Datos.ReferenciaWCF.DCAlumno[] consultar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/consultar", ReplyAction="http://tempuri.org/IWCFAlumno/consultarResponse")]
        System.Threading.Tasks.Task<Datos.ReferenciaWCF.DCAlumno[]> consultarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/consultarUno", ReplyAction="http://tempuri.org/IWCFAlumno/consultarUnoResponse")]
        Datos.ReferenciaWCF.DCAlumno consultarUno(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/consultarUno", ReplyAction="http://tempuri.org/IWCFAlumno/consultarUnoResponse")]
        System.Threading.Tasks.Task<Datos.ReferenciaWCF.DCAlumno> consultarUnoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/crear", ReplyAction="http://tempuri.org/IWCFAlumno/crearResponse")]
        Datos.ReferenciaWCF.DCAlumno crear();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/crear", ReplyAction="http://tempuri.org/IWCFAlumno/crearResponse")]
        System.Threading.Tasks.Task<Datos.ReferenciaWCF.DCAlumno> crearAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/editar", ReplyAction="http://tempuri.org/IWCFAlumno/editarResponse")]
        Datos.ReferenciaWCF.DCAlumno editar(Datos.ReferenciaWCF.DCAlumno dCAlumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/editar", ReplyAction="http://tempuri.org/IWCFAlumno/editarResponse")]
        System.Threading.Tasks.Task<Datos.ReferenciaWCF.DCAlumno> editarAsync(Datos.ReferenciaWCF.DCAlumno dCAlumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/eliminar", ReplyAction="http://tempuri.org/IWCFAlumno/eliminarResponse")]
        Datos.ReferenciaWCF.DCAlumno eliminar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFAlumno/eliminar", ReplyAction="http://tempuri.org/IWCFAlumno/eliminarResponse")]
        System.Threading.Tasks.Task<Datos.ReferenciaWCF.DCAlumno> eliminarAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFAlumnoChannel : Datos.ReferenciaWCF.IWCFAlumno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFAlumnoClient : System.ServiceModel.ClientBase<Datos.ReferenciaWCF.IWCFAlumno>, Datos.ReferenciaWCF.IWCFAlumno {
        
        public WCFAlumnoClient() {
        }
        
        public WCFAlumnoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFAlumnoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFAlumnoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFAlumnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Datos.ReferenciaWCF.DCAlumno[] consultar() {
            return base.Channel.consultar();
        }
        
        public System.Threading.Tasks.Task<Datos.ReferenciaWCF.DCAlumno[]> consultarAsync() {
            return base.Channel.consultarAsync();
        }
        
        public Datos.ReferenciaWCF.DCAlumno consultarUno(int id) {
            return base.Channel.consultarUno(id);
        }
        
        public System.Threading.Tasks.Task<Datos.ReferenciaWCF.DCAlumno> consultarUnoAsync(int id) {
            return base.Channel.consultarUnoAsync(id);
        }
        
        public Datos.ReferenciaWCF.DCAlumno crear() {
            return base.Channel.crear();
        }
        
        public System.Threading.Tasks.Task<Datos.ReferenciaWCF.DCAlumno> crearAsync() {
            return base.Channel.crearAsync();
        }
        
        public Datos.ReferenciaWCF.DCAlumno editar(Datos.ReferenciaWCF.DCAlumno dCAlumno) {
            return base.Channel.editar(dCAlumno);
        }
        
        public System.Threading.Tasks.Task<Datos.ReferenciaWCF.DCAlumno> editarAsync(Datos.ReferenciaWCF.DCAlumno dCAlumno) {
            return base.Channel.editarAsync(dCAlumno);
        }
        
        public Datos.ReferenciaWCF.DCAlumno eliminar(int id) {
            return base.Channel.eliminar(id);
        }
        
        public System.Threading.Tasks.Task<Datos.ReferenciaWCF.DCAlumno> eliminarAsync(int id) {
            return base.Channel.eliminarAsync(id);
        }
    }
}
